### PR TITLE
PRO-1672: Added Data Wrapper

### PR DESCRIPTION
**Pull request by kaushalrajbacancy**
## Description

- Added data wrapper and new services requires for the use of graphQL.
- Added new endpoints for the following services: Balances, Txn History, Swaps, Bridges, NFT metadata.

## How Has This Been Tested?

- It has been tested locally.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by ch4r10t33r — CHANGES_REQUESTED** [review]
Please enforce the use of an API key to in order to access the data api. If there is no APIKey, the data endpoints are not available.

**Review by ch4r10t33r — CHANGES_REQUESTED** [review]
Ensure the code is linted correctly.

**Review by ch4r10t33r — APPROVED** [review]
LGTM

**Review by vignesha22 — APPROVED** [review]

**Comment by ch4r10t33r** [comment]
Please address the conflicts.

**Pull request merged**
