### PR TITLE
Added getExchangeSupportedAssets endpoint

### PR DESCRIPTION
**Pull request by kaushalrajbacancy**
## Description

- Added `getExchangeSupportedAssets` to gets exchange supported tokens

## How Has This Been Tested?

- It has been tested locally.

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by ch4r10t33r — APPROVED** [review]

**Review by vignesha22 — APPROVED** [review]

**Comment by ch4r10t33r** [comment]
@kaushalrajbacancy Why isn't this merged yet??

**Comment by kaushalrajbacancy** [comment]
> @kaushalrajbacancy Why isn't this merged yet??

The PR hasn't been merged yet due to an issue with failing test cases in the SDK build.

**Comment by ch4r10t33r** [comment]
> > @kaushalrajbacancy Why isn't this merged yet??
> 
> The PR hasn't been merged yet due to an issue with failing test cases in the SDK build.

Who is addressing it?

**Comment by ch4r10t33r** [comment]
@kaushalrajbacancy Pls resolve the merge conflicts?

**Comment by kaushalrajbacancy** [comment]
> @kaushalrajbacancy Pls resolve the merge conflicts?

Okay

**Pull request merged**
