### PR TITLE
PRO - 1967 - GitHub issues

### PR DESCRIPTION
**Pull request by vignesha22**
## Description

- Updated paymaster url to accept arka api_key and chainId as queryString
- Added optional parameters such as entryPointAddress and Factory walletAddress for custom chain interaction
- Bug fixes for handling errors on connecting with custom chain interaction

## Types of changes
What types of changes does your code introduce?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Further comments (optional)

- https://github.com/etherspot/etherspot-prime-sdk/issues/59
- https://github.com/etherspot/etherspot-prime-sdk/issues/60
- https://github.com/etherspot/etherspot-prime-sdk/issues/61

### CODE REVIEW

**Comment by 0xSulpiride** [comment]
#64 addressed in the commit above

**Review by 0xSulpiride — APPROVED** [review]
LGTM
Can we also add scripts in package.json for the examples 16 and 19?

**Review by kaushalrajbacancy — APPROVED** [review]
LGTM

**Review by ch4r10t33r — APPROVED** [review]

**Comment by ch4r10t33r** [comment]
@vignesha22 Pls merge this ticket.

**Pull request merged**
